name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: pre-commit/action@v2.0.2

    - uses: google-github-actions/setup-gcloud@v0
    - name: Start GCP Datastore emulator
      # NOTE: this emulator is used by the tests below
      run: |
        gcloud components install --quiet beta cloud-datastore-emulator
        gcloud beta emulators datastore start --project foobar --host-port 0.0.0.0:8099 --consistency=1.0 --no-store-on-disk &

    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: pytest --color=yes --datastore_emulated
