name: CD

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build:
    if: github.repository_owner == 'related-sciences'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build a source distribution and a wheel
      run: |
        python -m build
        python -m twine check --strict dist/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist
    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
